# Generated by Django 3.0.8 on 2020-09-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finch',
            name='breed',
            field=models.CharField(default='sparrow', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finch',
            name='description',
            field=models.TextField(default='cute', max_length=25),
            preserve_default=False,
        ),
    ]
